# Generated by Django 4.1.2 on 2022-12-06 15:34

from django.db import migrations, models
import expenses.validators


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="money",
            field=models.IntegerField(
                default=1000, validators=[expenses.validators.validate_money]
            ),
        ),
    ]
